environment:
  matrix:
  - nodejs_version: "0.12"
  - nodejs_version: "1.0"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install
  - npm install --global .

test_script:
  - node --version
  - npm --version
  - npm test

# Don't actually build.
build: off
